USE [master]
GO

/****** Object:  Database [sifms]    Script Date: 31/03/2018 16:01:54 ******/
CREATE DATABASE [sifms]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sifms', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\sifms.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sifms_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\sifms_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [sifms] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sifms].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sifms] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sifms] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sifms] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sifms] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sifms] SET ARITHABORT OFF 
GO

ALTER DATABASE [sifms] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sifms] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sifms] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sifms] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sifms] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sifms] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sifms] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sifms] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sifms] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sifms] SET  ENABLE_BROKER 
GO

ALTER DATABASE [sifms] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sifms] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sifms] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sifms] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sifms] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sifms] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sifms] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sifms] SET RECOVERY FULL 
GO

ALTER DATABASE [sifms] SET  MULTI_USER 
GO

ALTER DATABASE [sifms] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sifms] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sifms] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sifms] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sifms] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sifms] SET QUERY_STORE = OFF
GO

USE [sifms]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [sifms] SET  READ_WRITE 
GO

